version: '3.5'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - botnet

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - botnet

  kafka-setup:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-setup
    depends_on:
      - kafka
    command: >
      bash -c "
      echo Waiting for Kafka to be ready... &&
      sleep 10 &&
      cub kafka-ready -b kafka:9093 1 20 &&
      kafka-topics --create --topic jokes --partitions 1 --replication-factor 1 --bootstrap-server kafka:9093
      "
    networks:
      - botnet

  scraper:
    build: "joke-scraper"
    container_name: scraper
    ports:
      - "8091:8091"
    depends_on:
      - kafka
    networks:
      - botnet
    environment:
      - KAFKA_HOST=kafka:9092
      - JOKE_TOPIC=jokes

networks:
  botnet:
    driver: bridge
    name: botnet