app: ''
bot: ''
database-platform: org.hibernate.dialect.PostgreSQLDialect
datasource: ''
description: Spring Boot Application
hibernate:
    ddl-auto: none
info: ''
init:
    mode: always
jpa: ''
name: Joke Bot
password: password
port: 8088
scraper: ''
server: ''
show-sql: true
spring: ''
sql: ''
token: ${BOT_TOKEN}
url: ${JOKE_SCRAPER_URL}
username: postgres
