spring:
  datasource:
    url: jdbc:postgresql://${DATA_SOURCE}/${POSTGRES_DB}
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
  #    show-sql: true
  sql:
    init.mode: always
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${KAFKA_GROUP_ID}
      properties:
        spring.json.value.default.type: com.odoyevsky.dto.CategoryJokes
      joke-topic: ${JOKE_TOPIC}

bot:
  name: RussianJokeBot
  token: ${BOT_TOKEN}
  commands:
    - command: "/joke"
      description: "случайная шутка"
    - command: "/categories"
      description: "список тем"
    - command: "/favourites"
      description: "избранные шутки"
    - command: "/help"
      description: "справочная информация"

server:
  port: 8098