spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/joke-bot
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: true
  sql:
    init.mode: always

bot:
  token: ${BOT_TOKEN}
  name: RussianJokeBot
server:
  port: 8088

server_path: "http://localhost:8087"